# -*- coding: utf-8 -*-
"""Optimizer Comparison on MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkQi_vsVB90bXThlxaAubBfz7kX6-2Ml
"""

# MIE424 Optimizer Comparison on MNIST

import math
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# 1. Reproducibility
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# 2. Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 3. Hyperparameters
BATCH_SIZE = 64
EPOCHS = 10

LR_CONFIG = {
    "SGD": 0.01,
    "Adam": 0.001,
    "RMSprop": 0.001,
}

SEEDS = [0, 1, 2, 3, 4]

# 4. Data
transform = transforms.ToTensor()

train_dataset = torchvision.datasets.MNIST(
    root="./data", train=True, download=True, transform=transform
)

test_dataset = torchvision.datasets.MNIST(
    root="./data", train=False, download=True, transform=transform
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# 5. Model
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        return self.net(x)

# 6. Helpers
def evaluate_accuracy(model):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return 100.0 * correct / total


def compute_weight_norm(model):
    total_sq_norm = 0.0
    with torch.no_grad():
        for param in model.parameters():
            total_sq_norm += torch.sum(param ** 2).item()
    return math.sqrt(total_sq_norm)

# 7. Training
def train_model(optimizer_name):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=LR_CONFIG["SGD"])
    elif optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=LR_CONFIG["Adam"])
    elif optimizer_name == "RMSprop":
        optimizer = optim.RMSprop(model.parameters(), lr=LR_CONFIG["RMSprop"])

    losses = []

    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0.0
        total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * labels.size(0)
            total += labels.size(0)

        avg_loss = running_loss / total
        losses.append(avg_loss)

    acc = evaluate_accuracy(model)
    norm = compute_weight_norm(model)

    return losses, acc, norm

# 8. Run Experiments
optimizers = ["SGD", "Adam", "RMSprop"]

all_results = {}

for opt in optimizers:
    print(f"\nRunning {opt}...")

    all_losses = []
    accs = []
    norms = []

    for seed in SEEDS:
        print(f"  Seed {seed}")
        set_seed(seed)
        losses, acc, norm = train_model(opt)

        all_losses.append(losses)
        accs.append(acc)
        norms.append(norm)

    # Convert to numpy
    all_losses = np.array(all_losses)

    all_results[opt] = {
        "mean_loss": np.mean(all_losses, axis=0),
        "std_loss": np.std(all_losses, axis=0),
        "mean_acc": np.mean(accs),
        "std_acc": np.std(accs),
        "mean_norm": np.mean(norms),
        "std_norm": np.std(norms),
    }

# 9. Print Table
print("\nFINAL RESULTS")
print("-" * 60)
print(f"{'Optimizer':<10} {'Acc Mean':<10} {'Acc Std':<10} {'Norm Mean':<12} {'Norm Std'}")
print("-" * 60)

for opt in optimizers:
    r = all_results[opt]
    print(f"{opt:<10} {r['mean_acc']:<10.2f} {r['std_acc']:<10.2f} {r['mean_norm']:<12.2f} {r['std_norm']:.2f}")

# 10. Plot Loss (Mean Curve)
plt.figure(figsize=(8, 5))

for opt in optimizers:
    mean = all_results[opt]["mean_loss"]
    std = all_results[opt]["std_loss"]

    epochs = range(1, EPOCHS + 1)

    plt.plot(epochs, mean, label=opt)
    plt.fill_between(epochs, mean - std, mean + std, alpha=0.2)

plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Training Loss (Mean ± Std)")
plt.legend()
plt.grid(True)
plt.show()

# 11. Accuracy Plot
means = [all_results[o]["mean_acc"] for o in optimizers]
stds = [all_results[o]["std_acc"] for o in optimizers]

plt.figure(figsize=(6, 4))
plt.bar(optimizers, means, yerr=stds, capsize=5)
plt.ylabel("Accuracy (%)")
plt.title("Test Accuracy (Mean ± Std)")
plt.grid(axis="y")
plt.show()

# 12. Weight Norm Plot
means = [all_results[o]["mean_norm"] for o in optimizers]
stds = [all_results[o]["std_norm"] for o in optimizers]

plt.figure(figsize=(6, 4))
plt.bar(optimizers, means, yerr=stds, capsize=5)
plt.ylabel("L2 Weight Norm")
plt.title("Weight Norm (Mean ± Std)")
plt.grid(axis="y")
plt.show()

from sklearn.decomposition import PCA
from scipy import stats
from itertools import combinations
from matplotlib.colors import ListedColormap, BoundaryNorm
from matplotlib.lines import Line2D

def train_model_with_tracking(optimizer_name):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=LR_CONFIG["SGD"])
    elif optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=LR_CONFIG["Adam"])
    elif optimizer_name == "RMSprop":
        optimizer = optim.RMSprop(model.parameters(), lr=LR_CONFIG["RMSprop"])

    losses = []
    grad_norms = []
    update_norms = []

    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0.0
        total = 0

        epoch_grad = []
        epoch_update = []

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()

            grad_sq = 0.0
            for p in model.parameters():
                if p.grad is not None:
                    grad_sq += torch.sum(p.grad.detach() ** 2).item()
            epoch_grad.append(math.sqrt(grad_sq))

            params_before = [p.detach().clone() for p in model.parameters()]
            optimizer.step()

            update_sq = 0.0
            for p_before, p_after in zip(params_before, model.parameters()):
                delta = p_after.detach() - p_before
                update_sq += torch.sum(delta ** 2).item()
            epoch_update.append(math.sqrt(update_sq))

            running_loss += loss.item() * labels.size(0)
            total += labels.size(0)

        losses.append(running_loss / total)
        grad_norms.append(np.mean(epoch_grad))
        update_norms.append(np.mean(epoch_update))

    acc = evaluate_accuracy(model)
    norm = compute_weight_norm(model)

    return {
        "model": model,
        "losses": losses,
        "acc": acc,
        "norm": norm,
        "grad_norms": grad_norms,
        "update_norms": update_norms,
    }

optimizers = ["SGD", "Adam", "RMSprop"]
tracked_results = {}

for opt in optimizers:
    all_losses = []
    accs = []
    norms = []
    grad_vals = []
    update_vals = []
    models = []

    for seed in SEEDS:
        set_seed(seed)
        result = train_model_with_tracking(opt)

        all_losses.append(result["losses"])
        accs.append(result["acc"])
        norms.append(result["norm"])
        grad_vals.append(result["grad_norms"])
        update_vals.append(result["update_norms"])
        models.append(result["model"])

    tracked_results[opt] = {
        "mean_loss": np.mean(all_losses, axis=0),
        "std_loss": np.std(all_losses, axis=0),
        "mean_acc": np.mean(accs),
        "std_acc": np.std(accs),
        "accs": np.array(accs),
        "mean_norm": np.mean(norms),
        "std_norm": np.std(norms),
        "norms": np.array(norms),
        "models": models,
        "mean_grad": np.mean(grad_vals, axis=0),
        "std_grad": np.std(grad_vals, axis=0),
        "mean_update": np.mean(update_vals, axis=0),
        "std_update": np.std(update_vals, axis=0),
    }

def extract_features(model, loader, max_samples=3000):
    model.eval()
    feats, labels = [], []
    count = 0

    with torch.no_grad():
        for images, y in loader:
            images = images.to(device)
            h = model.net[0:5](images)

            feats.append(h.cpu().numpy())
            labels.append(y.numpy())
            count += y.size(0)

            if count >= max_samples:
                break

    X = np.vstack(feats)[:max_samples]
    y = np.concatenate(labels)[:max_samples]
    return X, y


colors = [
    "#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00",
    "#ffff33", "#a65628", "#f781bf", "#999999", "#17becf"
]

cmap = ListedColormap(colors)
bounds = np.arange(-0.5, 10.5, 1)
norm = BoundaryNorm(bounds, cmap.N)

legend = [
    Line2D([0], [0], marker='o', color='w', label=str(i),
           markerfacecolor=colors[i], markersize=8)
    for i in range(10)
]

fig, axes = plt.subplots(3, 1, figsize=(6, 12))

for ax, opt in zip(axes, optimizers):
    model = tracked_results[opt]["models"][0]
    X, y = extract_features(model, test_loader)

    pca = PCA(n_components=2)
    X2 = pca.fit_transform(X)
    var = pca.explained_variance_ratio_

    ax.scatter(X2[:, 0], X2[:, 1], c=y, cmap=cmap, norm=norm, s=10, alpha=0.7)
    ax.set_title(opt)
    ax.set_xlabel(f"PC1 ({var[0]:.1%})")
    ax.set_ylabel(f"PC2 ({var[1]:.1%})")
    ax.grid(alpha=0.3)

fig.legend(
    handles=legend,
    title="Digit",
    loc="lower center",
    ncol=5,
    bbox_to_anchor=(0.5, -0.02)
)

plt.tight_layout(rect=[0, 0.05, 1, 1])
plt.show()

def get_weights(model):
    w = []
    for name, p in model.named_parameters():
        if "weight" in name:
            w.append(p.detach().cpu().numpy().ravel())
    return np.concatenate(w)

weights = {opt: get_weights(tracked_results[opt]["models"][0]) for opt in optimizers}
all_w = np.concatenate(list(weights.values()))
lim = np.max(np.abs(all_w))

fig, axes = plt.subplots(3, 1, figsize=(6, 12), sharex=True)

for i, (ax, opt) in enumerate(zip(axes, optimizers)):
    ax.hist(weights[opt], bins=80, range=(-0.6, 0.6))
    ax.set_title(opt)

    if i == 2:
        ax.set_xlabel("Weight value")

    ax.set_ylabel("Frequency")
    ax.set_xlim(-0.6, 0.6)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

epochs = np.arange(1, EPOCHS + 1)

plt.figure(figsize=(8, 5))
for opt in optimizers:
    m = tracked_results[opt]["mean_grad"]
    s = tracked_results[opt]["std_grad"]
    plt.plot(epochs, m, label=opt)
    plt.fill_between(epochs, m - s, m + s, alpha=0.2)

plt.xlabel("Epoch")
plt.ylabel("Gradient norm")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
for opt in optimizers:
    m = tracked_results[opt]["mean_update"]
    s = tracked_results[opt]["std_update"]
    plt.plot(epochs, m, label=opt)
    plt.fill_between(epochs, m - s, m + s, alpha=0.2)

plt.xlabel("Epoch")
plt.ylabel("Update norm")
plt.legend()
plt.grid(True)
plt.show()

def cohens_d(x, y):
    nx, ny = len(x), len(y)
    sx2, sy2 = np.var(x, ddof=1), np.var(y, ddof=1)
    pooled = np.sqrt(((nx - 1)*sx2 + (ny - 1)*sy2) / (nx + ny - 2))
    return (np.mean(x) - np.mean(y)) / pooled if pooled != 0 else np.nan


def run_stats(name, data):
    print("="*60)
    print(name)
    print("="*60)

    groups = [data[o] for o in optimizers]
    f, p = stats.f_oneway(*groups)
    print(f"ANOVA: F={f:.4f}, p={p:.6f}")

    pairs = list(combinations(optimizers, 2))
    alpha = 0.05 / len(pairs)

    for a, b in pairs:
        t, pval = stats.ttest_ind(data[a], data[b], equal_var=False)
        d = cohens_d(data[a], data[b])
        print(f"{a} vs {b}: p={pval:.6f}, d={d:.3f}, sig={pval < alpha}")

    print()


acc_data = {o: tracked_results[o]["accs"] for o in optimizers}
norm_data = {o: tracked_results[o]["norms"] for o in optimizers}

run_stats("Test Accuracy", acc_data)
run_stats("Weight Norm", norm_data)