# -*- coding: utf-8 -*-
"""Optimizer Comparison on MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkQi_vsVB90bXThlxaAubBfz7kX6-2Ml
"""

# MIE424 Optimizer Comparison on MNIST

import math
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# 1. Reproducibility
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# 2. Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 3. Hyperparameters
BATCH_SIZE = 64
EPOCHS = 10

LR_CONFIG = {
    "SGD": 0.01,
    "Adam": 0.001,
    "RMSprop": 0.001,
}

SEEDS = [0, 1, 2, 3, 4]

# 4. Data
transform = transforms.ToTensor()

train_dataset = torchvision.datasets.MNIST(
    root="./data", train=True, download=True, transform=transform
)

test_dataset = torchvision.datasets.MNIST(
    root="./data", train=False, download=True, transform=transform
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# 5. Model
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        return self.net(x)

# 6. Helpers
def evaluate_accuracy(model):
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return 100.0 * correct / total


def compute_weight_norm(model):
    total_sq_norm = 0.0
    with torch.no_grad():
        for param in model.parameters():
            total_sq_norm += torch.sum(param ** 2).item()
    return math.sqrt(total_sq_norm)

# 7. Training
def train_model(optimizer_name):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=LR_CONFIG["SGD"])
    elif optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=LR_CONFIG["Adam"])
    elif optimizer_name == "RMSprop":
        optimizer = optim.RMSprop(model.parameters(), lr=LR_CONFIG["RMSprop"])

    losses = []

    for epoch in range(EPOCHS):
        model.train()
        running_loss = 0.0
        total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * labels.size(0)
            total += labels.size(0)

        avg_loss = running_loss / total
        losses.append(avg_loss)

    acc = evaluate_accuracy(model)
    norm = compute_weight_norm(model)

    return losses, acc, norm

# 8. Run Experiments
optimizers = ["SGD", "Adam", "RMSprop"]

all_results = {}

for opt in optimizers:
    print(f"\nRunning {opt}...")

    all_losses = []
    accs = []
    norms = []

    for seed in SEEDS:
        print(f"  Seed {seed}")
        set_seed(seed)
        losses, acc, norm = train_model(opt)

        all_losses.append(losses)
        accs.append(acc)
        norms.append(norm)

    # Convert to numpy
    all_losses = np.array(all_losses)

    all_results[opt] = {
        "mean_loss": np.mean(all_losses, axis=0),
        "std_loss": np.std(all_losses, axis=0),
        "mean_acc": np.mean(accs),
        "std_acc": np.std(accs),
        "mean_norm": np.mean(norms),
        "std_norm": np.std(norms),
    }

# 9. Print Table
print("\nFINAL RESULTS")
print("-" * 60)
print(f"{'Optimizer':<10} {'Acc Mean':<10} {'Acc Std':<10} {'Norm Mean':<12} {'Norm Std'}")
print("-" * 60)

for opt in optimizers:
    r = all_results[opt]
    print(f"{opt:<10} {r['mean_acc']:<10.2f} {r['std_acc']:<10.2f} {r['mean_norm']:<12.2f} {r['std_norm']:.2f}")

# 10. Plot Loss (Mean Curve)
plt.figure(figsize=(8, 5))

for opt in optimizers:
    mean = all_results[opt]["mean_loss"]
    std = all_results[opt]["std_loss"]

    epochs = range(1, EPOCHS + 1)

    plt.plot(epochs, mean, label=opt)
    plt.fill_between(epochs, mean - std, mean + std, alpha=0.2)

plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Training Loss (Mean ± Std)")
plt.legend()
plt.grid(True)
plt.show()

# 11. Accuracy Plot
means = [all_results[o]["mean_acc"] for o in optimizers]
stds = [all_results[o]["std_acc"] for o in optimizers]

plt.figure(figsize=(6, 4))
plt.bar(optimizers, means, yerr=stds, capsize=5)
plt.ylabel("Accuracy (%)")
plt.title("Test Accuracy (Mean ± Std)")
plt.grid(axis="y")
plt.show()

# 12. Weight Norm Plot
means = [all_results[o]["mean_norm"] for o in optimizers]
stds = [all_results[o]["std_norm"] for o in optimizers]

plt.figure(figsize=(6, 4))
plt.bar(optimizers, means, yerr=stds, capsize=5)
plt.ylabel("L2 Weight Norm")
plt.title("Weight Norm (Mean ± Std)")
plt.grid(axis="y")
plt.show()